# Generated by Django 5.0.6 on 2024-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar.jpeg', upload_to='profile-images'),
        ),
    ]
